// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../pkg/mysql/mysql.go
//
// Generated by this command:
//
//	mockgen -source=../../../../pkg/mysql/mysql.go -destination=mocks_mysql_test.go -package=repo_test
//

// Package repo_test is a generated GoMock package.
package repo_test

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueryableTransaction is a mock of QueryableTransaction interface.
type MockQueryableTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockQueryableTransactionMockRecorder
	isgomock struct{}
}

// MockQueryableTransactionMockRecorder is the mock recorder for MockQueryableTransaction.
type MockQueryableTransactionMockRecorder struct {
	mock *MockQueryableTransaction
}

// NewMockQueryableTransaction creates a new mock instance.
func NewMockQueryableTransaction(ctrl *gomock.Controller) *MockQueryableTransaction {
	mock := &MockQueryableTransaction{ctrl: ctrl}
	mock.recorder = &MockQueryableTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryableTransaction) EXPECT() *MockQueryableTransactionMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockQueryableTransaction) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockQueryableTransactionMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockQueryableTransaction)(nil).ExecContext), varargs...)
}

// PrepareContext mocks base method.
func (m *MockQueryableTransaction) PrepareContext(arg0 context.Context, arg1 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", arg0, arg1)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockQueryableTransactionMockRecorder) PrepareContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockQueryableTransaction)(nil).PrepareContext), arg0, arg1)
}

// QueryContext mocks base method.
func (m *MockQueryableTransaction) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockQueryableTransactionMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockQueryableTransaction)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockQueryableTransaction) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockQueryableTransactionMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockQueryableTransaction)(nil).QueryRowContext), varargs...)
}
