volumes:
  mysql_data:

services:
  mysql:
    image: mysql:lts
    container_name: talka-mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./conf/mysql.conf:/etc/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
