// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=../usecase/mocks_gateways_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/AlexeyTarasov77/messanger.chats/internal/entity"
	gateways "github.com/AlexeyTarasov77/messanger.chats/internal/gateways"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsRepo is a mock of ChatsRepo interface.
type MockChatsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockChatsRepoMockRecorder
	isgomock struct{}
}

// MockChatsRepoMockRecorder is the mock recorder for MockChatsRepo.
type MockChatsRepoMockRecorder struct {
	mock *MockChatsRepo
}

// NewMockChatsRepo creates a new mock instance.
func NewMockChatsRepo(ctrl *gomock.Controller) *MockChatsRepo {
	mock := &MockChatsRepo{ctrl: ctrl}
	mock.recorder = &MockChatsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsRepo) EXPECT() *MockChatsRepoMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockChatsRepo) GetAll(ctx context.Context) ([]entity.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]entity.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockChatsRepoMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockChatsRepo)(nil).GetAll), ctx)
}

// Save mocks base method.
func (m *MockChatsRepo) Save(ctx context.Context, chat entity.Chat) (entity.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, chat)
	ret0, _ := ret[0].(entity.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockChatsRepoMockRecorder) Save(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockChatsRepo)(nil).Save), ctx, chat)
}

// UpdateLastMsgInfo mocks base method.
func (m *MockChatsRepo) UpdateLastMsgInfo(ctx context.Context, chatId int, msgText string, msgDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastMsgInfo", ctx, chatId, msgText, msgDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastMsgInfo indicates an expected call of UpdateLastMsgInfo.
func (mr *MockChatsRepoMockRecorder) UpdateLastMsgInfo(ctx, chatId, msgText, msgDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastMsgInfo", reflect.TypeOf((*MockChatsRepo)(nil).UpdateLastMsgInfo), ctx, chatId, msgText, msgDate)
}

// MockUsersRepo is a mock of UsersRepo interface.
type MockUsersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepoMockRecorder
	isgomock struct{}
}

// MockUsersRepoMockRecorder is the mock recorder for MockUsersRepo.
type MockUsersRepoMockRecorder struct {
	mock *MockUsersRepo
}

// NewMockUsersRepo creates a new mock instance.
func NewMockUsersRepo(ctrl *gomock.Controller) *MockUsersRepo {
	mock := &MockUsersRepo{ctrl: ctrl}
	mock.recorder = &MockUsersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepo) EXPECT() *MockUsersRepoMockRecorder {
	return m.recorder
}

// CheckExistsByIds mocks base method.
func (m *MockUsersRepo) CheckExistsByIds(ctx context.Context, ids []int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistsByIds", ctx, ids)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistsByIds indicates an expected call of CheckExistsByIds.
func (mr *MockUsersRepoMockRecorder) CheckExistsByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistsByIds", reflect.TypeOf((*MockUsersRepo)(nil).CheckExistsByIds), ctx, ids)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTransaction) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTransactionMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTransaction)(nil).Commit), ctx)
}

// Rollback mocks base method.
func (m *MockTransaction) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTransactionMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTransaction)(nil).Rollback), ctx)
}

// MockTransactionsManager is a mock of TransactionsManager interface.
type MockTransactionsManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionsManagerMockRecorder
	isgomock struct{}
}

// MockTransactionsManagerMockRecorder is the mock recorder for MockTransactionsManager.
type MockTransactionsManagerMockRecorder struct {
	mock *MockTransactionsManager
}

// NewMockTransactionsManager creates a new mock instance.
func NewMockTransactionsManager(ctrl *gomock.Controller) *MockTransactionsManager {
	mock := &MockTransactionsManager{ctrl: ctrl}
	mock.recorder = &MockTransactionsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionsManager) EXPECT() *MockTransactionsManagerMockRecorder {
	return m.recorder
}

// StartTransaction mocks base method.
func (m *MockTransactionsManager) StartTransaction(ctx context.Context) (gateways.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx)
	ret0, _ := ret[0].(gateways.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionsManagerMockRecorder) StartTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionsManager)(nil).StartTransaction), ctx)
}

// MockSlugGenerator is a mock of SlugGenerator interface.
type MockSlugGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSlugGeneratorMockRecorder
	isgomock struct{}
}

// MockSlugGeneratorMockRecorder is the mock recorder for MockSlugGenerator.
type MockSlugGeneratorMockRecorder struct {
	mock *MockSlugGenerator
}

// NewMockSlugGenerator creates a new mock instance.
func NewMockSlugGenerator(ctrl *gomock.Controller) *MockSlugGenerator {
	mock := &MockSlugGenerator{ctrl: ctrl}
	mock.recorder = &MockSlugGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugGenerator) EXPECT() *MockSlugGeneratorMockRecorder {
	return m.recorder
}

// GenerateRandomSlug mocks base method.
func (m *MockSlugGenerator) GenerateRandomSlug() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRandomSlug")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRandomSlug indicates an expected call of GenerateRandomSlug.
func (mr *MockSlugGeneratorMockRecorder) GenerateRandomSlug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRandomSlug", reflect.TypeOf((*MockSlugGenerator)(nil).GenerateRandomSlug))
}
