name: Shared reusable golang workflow
on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

permissions:
  contents: read


jobs:
  golangci-lint:
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=15m
          working-directory: ${{ inputs.workdir }}

  unit-tests:
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    name: runner / tests / unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Unit Tests
        run: go test -v ./...

  # integration-tests:
  #   name: runner / tests / integration
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Integration tests
  #       run: "make compose-up-integration-test"

